# Generated by Django 4.2.7 on 2025-03-23 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('descanso_inicio', models.TimeField(blank=True, null=True, verbose_name='Inicio de Descanso')),
                ('descanso_fin', models.TimeField(blank=True, null=True, verbose_name='Fin de Descanso')),
                ('lunes', models.BooleanField(default=True, verbose_name='Lunes')),
                ('martes', models.BooleanField(default=True, verbose_name='Martes')),
                ('miercoles', models.BooleanField(default=True, verbose_name='Miércoles')),
                ('jueves', models.BooleanField(default=True, verbose_name='Jueves')),
                ('viernes', models.BooleanField(default=True, verbose_name='Viernes')),
                ('sabado', models.BooleanField(default=False, verbose_name='Sábado')),
                ('domingo', models.BooleanField(default=False, verbose_name='Domingo')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
            },
        ),
        migrations.CreateModel(
            name='HistoricalHorario',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('descanso_inicio', models.TimeField(blank=True, null=True, verbose_name='Inicio de Descanso')),
                ('descanso_fin', models.TimeField(blank=True, null=True, verbose_name='Fin de Descanso')),
                ('lunes', models.BooleanField(default=True, verbose_name='Lunes')),
                ('martes', models.BooleanField(default=True, verbose_name='Martes')),
                ('miercoles', models.BooleanField(default=True, verbose_name='Miércoles')),
                ('jueves', models.BooleanField(default=True, verbose_name='Jueves')),
                ('viernes', models.BooleanField(default=True, verbose_name='Viernes')),
                ('sabado', models.BooleanField(default=False, verbose_name='Sábado')),
                ('domingo', models.BooleanField(default=False, verbose_name='Domingo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Horario',
                'verbose_name_plural': 'historical Horarios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDiaFestivo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('nacional', 'Nacional'), ('autonomico', 'Autonómico'), ('local', 'Local'), ('empresa', 'Empresa')], max_length=10, verbose_name='Tipo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Día Festivo',
                'verbose_name_plural': 'historical Días Festivos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DiaFestivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('nacional', 'Nacional'), ('autonomico', 'Autonómico'), ('local', 'Local'), ('empresa', 'Empresa')], max_length=10, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Día Festivo',
                'verbose_name_plural': 'Días Festivos',
                'ordering': ['fecha'],
                'unique_together': {('fecha', 'tipo')},
            },
        ),
    ]
