# Generated by Django 4.2.7 on 2025-03-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('accounts', '0002_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='authorized_companies',
            field=models.ManyToManyField(blank=True, to='core.company'),
        ),
    ]
